import type { ValidationReport } from "./types";

/**
 * Base URL of the Java quality engine. Configuration, not a hardcoded
 * `localhost:8080` -- same principle as `quality-rules.yml` and
 * `WG_QUALITY_API_URL` on the Python side: a deployed frontend only needs an
 * env var change, never a rebuild.
 */
const QUALITY_API_URL: string =
  (import.meta.env.VITE_QUALITY_API_URL as string | undefined) ?? "http://localhost:8080";

/**
 * `import.meta.env.BASE_URL`, not a bare "/data/...": on GitHub Pages this
 * site is served under /WealthGuard/ (see vite.config.ts), so an absolute
 * "/data/..." path would 404 there even though it works fine in local dev
 * where the base is "/".
 */
const ASSET_BASE = import.meta.env.BASE_URL;

export type ReportSource = "live" | "demo";

export interface LoadedReport {
  report: ValidationReport;
  source: ReportSource;
}

async function loadFixture(): Promise<unknown> {
  const response = await fetch(`${ASSET_BASE}data/validate-request.json`);
  if (!response.ok) {
    throw new Error(
      `Could not load the demo request body (${response.status}). ` +
        "Run `wg-export-frontend-fixture` in data-pipeline first."
    );
  }
  return response.json();
}

/**
 * Calls the Java engine directly from the browser (cahier des charges §2.5:
 * "en temps reel via l'API Java"), not a pre-computed report. The request
 * body is a static fixture exported from the seed dataset by
 * `wealthguard_pipeline.seed.export_frontend_fixture` -- in a real deployment
 * this would instead be whatever batch a backend just ingested, but the
 * engine call itself is identical either way.
 *
 * A short timeout matters specifically for the GitHub Pages deployment: a
 * visitor there has no engine running on their own machine at all, and
 * without an explicit abort the browser can take a while to give up on
 * `localhost` before `loadReport()` can fall back to the demo snapshot.
 */
async function fetchLiveValidationReport(): Promise<ValidationReport> {
  const requestBody = await loadFixture();

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 4000);
  try {
    const response = await fetch(`${QUALITY_API_URL}/api/v1/validate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody),
      signal: controller.signal,
    });
    if (!response.ok) {
      throw new Error(
        `The quality engine at ${QUALITY_API_URL} returned ${response.status} ${response.statusText}.`
      );
    }
    return (await response.json()) as ValidationReport;
  } finally {
    clearTimeout(timeout);
  }
}

/**
 * A frozen snapshot of a real validation run, generated by POSTing the same
 * fixture to a locally running engine (see `frontend/public/data/README` --
 * regenerate with the `curl` one-liner there whenever the seed dataset
 * changes). Used only when the live engine is unreachable, which is the
 * normal case for a visitor to the public GitHub Pages deployment: nobody
 * else has this project's Java engine running on their machine.
 */
async function fetchDemoReport(): Promise<ValidationReport> {
  const response = await fetch(`${ASSET_BASE}data/demo-report.json`);
  if (!response.ok) {
    throw new Error(`Could not load the demo report snapshot either (${response.status}).`);
  }
  return (await response.json()) as ValidationReport;
}

/** Live first, frozen demo snapshot second -- see fetchLiveValidationReport's docstring. */
export async function loadReport(): Promise<LoadedReport> {
  try {
    const report = await fetchLiveValidationReport();
    return { report, source: "live" };
  } catch {
    const report = await fetchDemoReport();
    return { report, source: "demo" };
  }
}
